import { ChainConfig } from "../../models/Chain";
import { getRpcUrls } from "./rpcs";

export type ChainType = "near" | "sol" | "evm" | "tron" | "aptos";

export const chainTypes: Record<ChainType, { value: ChainType; name: string; color: string; }> = {
  near: {
    value: "near",
    name: "Near",
    color: "#56DEAD",
  },
  sol: {
    value: "sol",
    name: "Solana",
    color: "#987FF3",
  },
  evm: {
    value: "evm",
    name: "EVM",
    color: "#C4CAE1",
  },
  tron: {
    value: "tron",
    name: "Tron",
    color: "#F66273",
  },
  aptos: {
    value: "aptos",
    name: "Aptos",
    color: "#000000",
  },
};

const chains: Record<string, ChainConfig> = {
  near: {
    chainName: "Near",
    blockchain: "near",
    chainIcon: "/chains/near.png",
    chainIconGray: "/chains/near-gray.png",
    chainType: chainTypes.near.value,
    blockExplorerUrl: "https://nearblocks.io/txns",
    primaryColor: "#76EA9E",
    nativeToken: {
      symbol: "NEAR",
      decimals: 24,
    },
    rpcUrls: getRpcUrls("near"),
  },
  sol: {
    chainName: "Solana",
    blockchain: "sol",
    chainIcon: "/chains/solana.png",
    chainIconGray: "/chains/solana-gray.png",
    chainType: chainTypes.sol.value,
    blockExplorerUrl: "https://solscan.io/tx",
    primaryColor: "#B93EF0",
    nativeToken: {
      symbol: "SOL",
      decimals: 9,
    },
    rpcUrls: getRpcUrls("sol"),
  },
  eth: {
    chainName: "Ethereum",
    blockchain: "eth",
    chainIcon: "/chains/ethereum.png",
    chainIconGray: "/chains/ethereum-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 1,
    blockExplorerUrl: "https://etherscan.io/tx",
    primaryColor: "#7083ee",
    nativeToken: {
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: getRpcUrls("eth"),
  },
  arb: {
    chainName: "Arbitrum",
    blockchain: "arb",
    chainIcon: "/chains/arbitrum.png",
    chainIconGray: "/chains/arbitrum-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 42161,
    blockExplorerUrl: "https://arbiscan.io/tx",
    primaryColor: "#4763A7",
    nativeToken: {
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: getRpcUrls("arb"),
  },
  bsc: {
    chainName: "BNB Chain",
    blockchain: "bsc",
    chainIcon: "/chains/bsc.png",
    chainIconGray: "/chains/bsc-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 56,
    blockExplorerUrl: "https://bscscan.com/tx",
    primaryColor: "#F1C144",
    nativeToken: {
      symbol: "BNB",
      decimals: 18,
    },
    rpcUrls: getRpcUrls("bsc"),
  },
  avax: {
    chainName: "Avalanche",
    blockchain: "avax",
    chainIcon: "/chains/avalanche.png",
    chainIconGray: "/chains/avalanche-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 43114,
    blockExplorerUrl: "https://snowtrace.io/tx",
    primaryColor: "#9D2620",
    nativeToken: {
      symbol: "AVAX",
      decimals: 18,
    },
    rpcUrls: getRpcUrls("avax"),
  },
  base: {
    chainName: "Base",
    blockchain: "base",
    chainIcon: "/chains/base.png",
    chainIconGray: "/chains/base-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 8453,
    blockExplorerUrl: "https://basescan.org/tx",
    primaryColor: "#3137F6",
    nativeToken: {
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: getRpcUrls("base"),
  },
  pol: {
    chainName: "Polygon",
    blockchain: "pol",
    chainIcon: "/chains/polygon.png",
    chainIconGray: "/chains/polygon-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 137,
    blockExplorerUrl: "https://polygonscan.com/tx",
    primaryColor: "#5A2AD1",
    nativeToken: {
      symbol: "POL",
      decimals: 18,
    },
    rpcUrls: getRpcUrls("pol"),
  },
  gnosis: {
    chainName: "Gnosis",
    blockchain: "gnosis",
    chainIcon: "/chains/gnosis.png",
    chainIconGray: "/chains/gnosis-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 100,
    blockExplorerUrl: "https://gnosisscan.io/tx",
    primaryColor: "#285230",
    nativeToken: {
      symbol: "XDAI",
      decimals: 18,
    },
    rpcUrls: getRpcUrls("gnosis"),
  },
  op: {
    chainName: "Optimism",
    blockchain: "op",
    chainIcon: "/chains/optimism.png",
    chainIconGray: "/chains/optimism-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 10,
    blockExplorerUrl: "https://optimistic.etherscan.io/tx",
    primaryColor: "#B5271D",
    nativeToken: {
      symbol: "ETH",
      decimals: 18,
    },
    rpcUrls: getRpcUrls("op"),
  },
  tron: {
    chainName: "Tron",
    blockchain: "tron",
    chainIcon: "/chains/tron.png",
    chainIconGray: "/chains/tron-gray.png",
    chainType: chainTypes.tron.value,
    blockExplorerUrl: "https://tronscan.org/tx",
    primaryColor: "#BC3221",
    nativeToken: {
      symbol: "TRX",
      decimals: 6,
    },
    rpcUrls: getRpcUrls("tron"),
  },
  aptos: {
    chainName: "Aptos",
    blockchain: "aptos",
    chainIcon: "/chains/aptos.png",
    chainIconGray: "/chains/aptos-gray.png",
    chainType: chainTypes.aptos.value,
    blockExplorerUrl: "https://aptoscan.com/transaction",
    primaryColor: "#000000",
    nativeToken: {
      symbol: "APT",
      decimals: 8,
    },
    rpcUrls: getRpcUrls("aptos"),
  },
  bera: {
    chainName: "Berachain",
    blockchain: "bera",
    chainIcon: "/chains/berachain.png",
    chainIconGray: "/chains/berachain-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 80094,
    blockExplorerUrl: "https://berascan.com/tx/",
    primaryColor: "#F37325",
    nativeToken: {
      symbol: "BERA",
      decimals: 18,
    },
    rpcUrls: getRpcUrls("bera"),
  },
  xlayer: {
    chainName: "X Layer",
    blockchain: "xlayer",
    chainIcon: "/chains/xlayer.png",
    chainIconGray: "/chains/xlayer-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 196,
    blockExplorerUrl: "https://www.oklink.com/xlayer/tx/",
    primaryColor: "#000000",
    nativeToken: {
      symbol: "OKB",
      decimals: 18,
    },
    rpcUrls: getRpcUrls("xlayer"),
  },
  plasma: {
    chainName: "Plasma",
    blockchain: "plasma",
    chainIcon: "/chains/plasma.png",
    chainIconGray: "/chains/plasma-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 9745,
    blockExplorerUrl: "https://plasmascan.to/tx/",
    primaryColor: "#162F29",
    nativeToken: {
      symbol: "XPL",
      decimals: 18,
    },
    rpcUrls: getRpcUrls("plasma"),
  },
};

export default chains;
